dependencies:
  # - <organisation/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.3.3

compiler:
  solc:
    optimizer:
      enabled: true
      runs: 800
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'
    

networks:
  development:
    cmd_settings:
      default_balance: 100000
  